ProjectData.rawProjectData = [
  {
    name:"Cakelabs 3",
    startDate:"//~2015",
    endDate:"//~2015",
    description:"A tiny 'game' where you eat weird pastries.",
    completeness:"60",
    tags:"website,game",
    effort:"1",
    image:"cakelabs",
    creators:"lance",
    link:"pages/cakelabs/cakelabs3.html"
  },
  {
    name:"Nihonese",
    startDate:"12/10/2020",
    endDate:"7/2/2021",
    description:"A silly japanese learning tool.",
    completeness:"100",
    tags:"language,website,game",
    effort:"1",
    image:"nihonese",
    creators:"lance",
    link:"https://electriclance-edu.github.io/nihonese/"
  },
  {
    name:"Dead People Arriving Places",
    startDate:"23/2/2020",
    endDate:"/4/2020",
    description:"Three friends running a pitstop in the middle of galactic nowhere.",
    completeness:"5",
    tags:"art,story",
    effort:"1",
    image:"deadPeople",
    creators:"lance",
    link:"none"
  },
  {
    name:"EepOS",
    startDate:"/~11/2020",
    endDate:"/11/2020",
    description:"The greatest javascript-based operating system, coming near you.",
    completeness:"25",
    tags:"website,game",
    effort:"2",
    image:"eepos",
    creators:"lance",
    link:"pages/eepos/index.html"
  },
  {
    name:"We Do It Better than Icarus Ever Could",
    startDate:"start/~8/2020",
    endDate:"middle/11/2020",
    description:"Explore a dying galaxy. Currently just a spinny planet generator.",
    completeness:"15",
    tags:"website,game",
    effort:"1",
    image:"icarus",
    creators:"lance",
    link:"https://electriclance.itch.io/icarus"
  },
  {
    name:"Fishing!",
    startDate:"~25/~5/2020",
    endDate:"~6/~6/2020",
    description:"A typing fishing game. Based on an unnamed mmorpg's fishing system.",
    completeness:"50",
    tags:"website,game",
    effort:"2",
    image:"fishingGame",
    creators:"lance,sam",
    link:"https://electriclance.itch.io/fishing"
  },
  {
    name:"'Waste of Time' the particle simulator",
    startDate:"26/10/2020",
    endDate:"27/10/2020",
    description:"A falling-sand simulator made in a day. Which is why it's crap.",
    completeness:"60",
    tags:"website,game",
    effort:"3",
    image:"particleSim",
    creators:"lance",
    link:"pages/particles/index.html"
  },
  {
    name:"Burger Stand",
    startDate:"29/12/2020",
    endDate:"5/1/2021",
    description:"Make burgers.",
    completeness:"30",
    tags:"website,game",
    effort:"2",
    image:"burgerStand",
    creators:"lance",
    link:"https://electriclance.itch.io/borger-game"
  },
  {
    name:"Sterile Neutrinos: A Hidden Unknown",
    startDate:"middle/~5/2020",
    endDate:"15/6/2020",
    description:"A really badly made science video submitted for a competition. Score reached the 40th percentile ;D",
    completeness:"100",
    tags:"video",
    effort:"1",
    image:"sterileNeutrino",
    creators:"lance",
    link:"https://www.youtube.com/watch?v=bbBcJGz7as4"
  },
  {
    name:"Experiment #32",
    startDate:"~26/2/2021",
    endDate:"3/29/2021",
    description:"Some research logs and spirits chronicling a junior librarian's attempt at commnading plants to do things.",
    completeness:"30",
    tags:"story,mostly-text",
    effort:"2",
    image:"none",
    creators:"lance",
    link:"https://docs.google.com/document/d/1BwzwAxvnyR_qhXu614D2qTXRmjGWLHbPyBZpDe1g2wM/edit?usp=sharing"
  },
  {
    name:"Satose (Hurezu Kalii)",
    startDate:"~26/2/2021",
    endDate:"ongoing",
    description:"A terrible conlang. But a pretty good name generator. (name subject to change)",
    completeness:"25",
    tags:"language,mostly-text",
    effort:"1",
    image:"none",
    creators:"lance",
    link:"https://docs.google.com/document/d/1LmgwFboIr2Te5oEwcSh4QRUY5xjxez0pI-lQVsGE93U/edit?usp=sharing"
  },
  {
    name:"Kalimba",
    startDate:"/~8/2020",
    endDate:"3/29/2021",
    description:"A quaint little village by a small, quiet sea. Part of an on-hiatus minecraft roleplay.",
    completeness:"40",
    tags:"story,roleplay",
    effort:"1",
    image:"kalimba",
    creators:"lance",
    link:"https://docs.google.com/document/d/1b417BJDYZn3oYqGrFC-HPABsWIlaxH0NYRgodZUXsz0/edit?usp=sharing"
  },
  {
    name:"The Ezelhan Documentation of Foreign Ships",
    startDate:"/~7/2020",
    endDate:"14/7/2020",
    description:"Drew a few ship designs, made them in cardboard, and wrote some lore for them.",
    completeness:"100",
    tags:"story,mostly-text,crafts",
    effort:"3",
    image:"none",
    creators:"lance,liam",
    link:"https://docs.google.com/document/d/1Nr0ONyHjIG49zUQWcW9U3KIBO8SklFriG5HObeZrKKY/edit?usp=sharing"
  },
  {
    name:"colorless gold",
    startDate:"5/10/2020",
    endDate:"6/10/2020",
    description:"<i>\"There are colors beyond human comprehension.\"</i> The story of an intern at the Chromatics Department.",
    completeness:"5",
    tags:"story,mostly-text",
    effort:"3",
    image:"none",
    creators:"lance",
    link:"none"
  },
  {
    name:"The Wovenstrong Dual",
    startDate:"~2/12/2020",
    endDate:"middle/12/2020",
    description:"A grand nation spanning two galaxies, born from the union of two wholly different cultures. Unrelated to Kalimba.",
    completeness:"60",
    tags:"story,mostly-text,roleplay",
    effort:"3",
    image:"none",
    creators:"lance",
    link:"https://docs.google.com/document/d/1UtpnHYyVXvpLualMXeMb2MNCiCPngeFVuvSfrj8752Q/edit"
  },
  {
    name:"Higurashi but Stupid",
    startDate:"10/6/2020",
    endDate:"10/6/2020",
    description:"A beautiful pixel-art poster commemorating a great anime.",
    completeness:"100",
    tags:"art",
    effort:"3",
    image:"higurashiPoster",
    creators:"lance",
    link:"images/projectPages/higurashiPoster.png"
  },
  {
    name:"ASS - UGH UGH",
    startDate:"start/3/2020",
    endDate:"~4/9/2020",
    description:"(pronounced ASS - ɻçʝxɣχʁħʕhɦ) The Universal Government of Hornies Uterus Go Hard. Beauty incarnate.",
    completeness:"100",
    tags:"story,mostly-text,hidden",
    effort:"2",
    image:"ughUgh",
    creators:"lance,lauren,justice",
    link:"https://classroom.google.com/u/0/c/NTI5ODI5ODg0NDRa"
  },
  {
    name:"Constructures",
    startDate:"mid/12/2019",
    endDate:"~12/3/2020",
    description:"A supplementary for any verbal roleplay, designed to keep track of custom resources, characters, etc.",
    completeness:"10",
    tags:"roleplay,website,game",
    effort:"2",
    image:"none",
    creators:"lance",
    link:"pages/constructures/index.html"
  },
  {
    name:"One Mile",
    startDate:"middle/4/2020",
    endDate:"/~6/2020",
    description:"Massive creatures walk across an infinite plane, carrying the remnants of humanity away from an ever expanding darkness.",
    completeness:"5",
    tags:"story,mostly-text",
    effort:"2",
    image:"none",
    creators:"lance",
    link:"https://docs.google.com/presentation/d/1qKVAiDjrt9pGVVhJHo_tJyrk9-zgtUSoQNzppLWyHNA/edit?usp=sharing"
  },
  {
    name:"One Mile + 1",
    startDate:"16/2/2021",
    endDate:"hiatus",
    description:"A rebooted version of One Mile because the concept was nice.",
    completeness:"5",
    tags:"story,mostly-text",
    effort:"3",
    image:"none",
    creators:"lance",
    link:"https://docs.google.com/document/d/1eHO34vPjzTft74AOEiVYu_d8W05oYw7ryAsBi54j65E/edit?usp=sharing"
  },
  {
    name:"Aea",
    startDate:"/~2/2020",
    endDate:"/3/2020",
    description:"The evolutionary tree of a world named Aea. Lots of lines. Also has some lore.",
    completeness:"100",
    tags:"art",
    effort:"1",
    image:"aeaEvolutionTree",
    creators:"lance",
    link:"images/projectPages/aea.png"
  },
  {
    name:"Cookies and Crickets",
    startDate:"2/2/2021",
    endDate:"24/2/2021",
    description:"A man finds himself alone in a seemingly endless, alien desert.",
    completeness:"15",
    tags:"art,story,mostly-text",
    effort:"2",
    image:"cookiesAndCrickets",
    creators:"lance",
    link:"https://docs.google.com/document/d/1rt3g30hM1M3ZhhWBQSAZWFQ4AmseBShu2UwE_yVm8Ks/edit?usp=sharing"
  },
  {
    name:"Stories and Snippets/Soul",
    startDate:"14/10/2020",
    endDate:"/1/2021",
    description:"Many, many attempts at extending Sam's 'soul' concept.",
    completeness:"30",
    tags:"story,mostly-text",
    effort:"2",
    image:"none",
    creators:"lance,sam",
    link:"https://docs.google.com/document/d/1U1UrhYgHx5DAsEUCxMAM85ORuv7DuxH9fD9mHkhxoik/edit?usp=sharing"
  },
  {
    name:"Hexagonland",
    startDate:"/~2/2021",
    endDate:"end/~2/2021",
    description:"A recently-awakened god tries to bring back life to their ruined, deserted world.",
    completeness:"10",
    tags:"story,game,website",
    effort:"3",
    image:"hexagonland",
    creators:"lance",
    link:"pages/hexagons/index.html"
  },
  {
    name:"Starbound",
    startDate:"day/month/2020",
    endDate:"day/month/2020",
    description:"A man reminisces atop a mountain.",
    completeness:"100",
    tags:"art,story",
    effort:"2",
    image:"starboundComic",
    creators:"lance",
    link:"images/projectPages/starbound.png"
  },
  {
    name:"734 Words",
    startDate:"27/5/2020",
    endDate:"28/5/2020",
    description:"A tragic tale written in a poetic style reminiscent of the great epics of old.",
    completeness:"100",
    tags:"mostly-text,story",
    effort:"3",
    image:"peppaPig",
    creators:"lance",
    link:"https://docs.google.com/document/d/106w2eQHWFBXqThWNoDV2ia7JkLT2AbcNd2UWfhZgEX8/edit?usp=sharing"
  },
  {
    name:"Projectland",
    startDate:"18/3/2021",
    endDate:"ongoing",
    description:"A listing of me and my friends' projects.",
    completeness:"10",
    tags:"website",
    effort:"2",
    image:"projectland",
    creators:"lance",
    link:"special"
  },
  {
    name:"Da Estorya",
    startDate:"8/3/2021",
    endDate:"/3/2021",
    description:"A little writing experiment where one person writes a page, then the second writes the next, then back to the first person, and so on.",
    completeness:"10",
    tags:"story,mostly-text",
    effort:"2",
    image:"none",
    creators:"lance,liam",
    link:"https://docs.google.com/document/d/1vSWMK33nYllq32JHiF209JsOId_qluG8qRrDfSzIqfc/edit?usp=sharing"
  },
  {
    name:"CS1 Project",
    startDate:"/~1/2019",
    endDate:"/~2/2019",
    description:"Grade 7 CS project. A very badly done self-introduction.",
    completeness:"100",
    tags:"website",
    effort:"1",
    image:"csOne",
    creators:"lance,liam",
    link:"><><"
  },
  {
    name:"Space Archives",
    startDate:"middle/3/2020",
    endDate:"middle/3/2020",
    description:"Some tales set in space. Actually only one tale.",
    completeness:"10",
    tags:"story,mostly-text",
    effort:"2",
    image:"spaceArchives",
    creators:"lance,liam",
    link:"><><"
  },
  {
    name:"ValEd 2 Game",
    startDate:"//2018",
    endDate:"//2018",
    description:"Match the presented moral value with an act that embodies it.",
    completeness:"10",
    tags:"story,mostly-text",
    effort:"2",
    image:"valEdTwo",
    creators:"lance",
    link:"><><"
  },
  {
    name:"Potato Incremental",
    startDate:"/~3/2016",
    endDate:"/~3/2016",
    description:"A very old attempt at creating a game.",
    completeness:"10",
    tags:"website,game",
    effort:"3",
    image:"none",
    creators:"lance",
    link:"><><"
  },
  {
    name:"Space Mining Game",
    startDate:"/~3/2020",
    endDate:"/3/2020",
    description:"\"You wake up on a landscape of rock and dust, dimly lit by a distant star. The surface of an asteroid, one you just crash landed on.\"",
    completeness:"10",
    tags:"story,game,website",
    effort:"2",
    image:"none",
    creators:"lance",
    link:"><><"
  },
  {
    name:"Eevolutoon Simulator",
    startDate:"middle/~9/2019",
    endDate:"/~9/2019",
    description:"An attempt at trying to simulate an ecosystem of evolving organisms.",
    completeness:"30",
    tags:"website,game",
    effort:"2",
    image:"eevolutoon",
    creators:"lance",
    link:"><><"
  },
  {
    name:"Eevolutoon Simulator: Reborn",
    startDate:"3/29/2021",
    endDate:"/3/2021",
    description:"A new go at trying to simulate evolution one and a half years later.",
    completeness:"0",
    tags:"website,game",
    effort:"3",
    image:"eevolutoonReborn",
    creators:"lance",
    link:"><><"
  },
  {
    name:"BJC Submissions: 2021",
    startDate:"4/1/2021",
    endDate:"",
    description:"This year's attempt at making a good science video.",
    completeness:"0",
    tags:"video",
    effort:"1",
    image:"none",
    creators:"lance,liam",
    link:"><><"
  },
  {
    name:"Project Blobbees",
    startDate:"start/1/2020",
    endDate:"/~1/2020",
    description:"The dream of a castlevania/metroid/hollow knight-type game. Alas, the vision sputtered out before it even left the ground.",
    completeness:"1",
    tags:"game,story",
    effort:"3",
    image:"none",
    creators:"lance",
    link:"><><"
  },
  {
    name:"Wewercian (Kimispeak)",
    startDate:"2/21/2021",
    endDate:"ongoing",
    description:"Kimi constructs a conlang.",
    completeness:"33",
    tags:"language,mostly-text",
    effort:"1",
    image:"none",
    creators:"kimi",
    link:"https://docs.google.com/document/d/113L1eyBsbKiHyJ0cEfCoS-gWzyeDcFOOSGzpXgl5380/edit?usp=sharing"
  },
  {
    name:"The Museum Unintelligible",
    startDate:"//2020",
    endDate:"//2020",
    description:"Please visit the Museum.",
    completeness:"100",
    tags:"art,website",
    effort:"1",
    image:"museumUnintelligible",
    creators:"kimi",
    link:"https://kimidom.github.io/The-Museum-Unintelligible/index.html"
  }
]
